apiVersion: v1
kind: Service
metadata:
  name: vue-fe-service
  namespace: app
  labels:
    app: vue-fe
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30890
      protocol: TCP
      name: http
  selector:
    app: vue-fe